# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

applym <- function(x, margin, s) {
    .Call('_pcamix2_applym', PACKAGE = 'pcamix2', x, margin, s)
}

isNA <- function(x) {
    .Call('_pcamix2_isNA', PACKAGE = 'pcamix2', x)
}

missing_mean <- function(C1) {
    .Call('_pcamix2_missing_mean', PACKAGE = 'pcamix2', C1)
}

applymissingmean <- function(x, margin) {
    .Call('_pcamix2_applymissingmean', PACKAGE = 'pcamix2', x, margin)
}

myscale <- function(x, mu, sd) {
    .Call('_pcamix2_myscale', PACKAGE = 'pcamix2', x, mu, sd)
}

myrecodquant <- function(X) {
    .Call('_pcamix2_myrecodquant', PACKAGE = 'pcamix2', X)
}

sweepS <- function(x, y, marg) {
    .Call('_pcamix2_sweepS', PACKAGE = 'pcamix2', x, y, marg)
}

sweepM <- function(a, b, n) {
    .Call('_pcamix2_sweepM', PACKAGE = 'pcamix2', a, b, n)
}

sweepD <- function(a, b, n) {
    .Call('_pcamix2_sweepD', PACKAGE = 'pcamix2', a, b, n)
}

mysvd <- function(x) {
    .Call('_pcamix2_mysvd', PACKAGE = 'pcamix2', x)
}

myqrrank <- function(x) {
    .Call('_pcamix2_myqrrank', PACKAGE = 'pcamix2', x)
}

rcppeigen_hello_world <- function() {
    .Call('_pcamix2_rcppeigen_hello_world', PACKAGE = 'pcamix2')
}

rcppeigen_outerproduct <- function(x) {
    .Call('_pcamix2_rcppeigen_outerproduct', PACKAGE = 'pcamix2', x)
}

rcppeigen_innerproduct <- function(x) {
    .Call('_pcamix2_rcppeigen_innerproduct', PACKAGE = 'pcamix2', x)
}

rcppeigen_bothproducts <- function(x) {
    .Call('_pcamix2_rcppeigen_bothproducts', PACKAGE = 'pcamix2', x)
}

